- hosts: localhost
  tasks:
    - name: create docker image
      command: docker build -t hello:latest .

    - name: create tag to push image onto dockerhub
      command: docker tag hello:latest vgik/devops3:latest

    - name: push docker image into dockerhub
      command: docker push vgik/devops3:latest